version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=15893587max
      - POSTGRES_DB=production
      - TZ="Europe\Moscow"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    restart: always