# Generated by Django 4.1.3 on 2022-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
