# Generated by Django 4.1.3 on 2022-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0004_order_is_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_issued',
        ),
        migrations.AddField(
            model_name='order',
            name='issuing_time',
            field=models.DateTimeField(null=True),
        ),
    ]
