# Generated by Django 4.1.3 on 2022-12-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0006_historyorder_queueorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueueOrder',
        ),
    ]
