# Generated by Django 4.1.3 on 2022-12-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0007_delete_queueorder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historyorder',
            table='order_history_view',
        ),
    ]
