# Generated by Django 4.1.3 on 2022-12-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0010_historyorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyorder',
            options={'managed': False},
        ),
    ]
