# Generated by Django 4.1.3 on 2022-12-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0011_alter_historyorder_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOrder',
        ),
    ]
