# Generated by Django 4.1.3 on 2022-12-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0015_historyorder_queueorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOrder',
        ),
        migrations.DeleteModel(
            name='QueueOrder',
        ),
    ]
