# Generated by Django 4.1.3 on 2022-12-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_conveyor', '0016_delete_historyorder_delete_queueorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.IntegerField()),
                ('cell', models.IntegerField()),
                ('items', models.JSONField()),
                ('issuing_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
